filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

setup.kibana:
  host: kib:5601

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

setup.template.overwrite: true
setup.template.append_fields:
- name: line_str
  type: keyword

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - drop_fields:
      fields: ["split_tokens"]
      ignore_missing: true

filebeat.inputs:
  - type: log
    index: mongo
    tags: ["mongo_json"]
    json:
      keys_under_root: true
    paths:
      - /usr/share/filebeat/mongo/*.json