filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

setup.kibana:
  host: kib:5601

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

processors:
  - drop_fields:
      fields: ["split_tokens"]
      ignore_missing: true

filebeat.inputs:
  - type: log
    index: mongo
    json:
      keys_under_root: true
    paths:
      - /usr/share/filebeat/mongo/*.json

setup.template.pattern: "mongo*"
setup.template.overwrite: true
setup.template.json.name: "mongo"
setup.template.json.enabled: true
setup.template.json.path: "filebeat.template.json"

logging.level: info
logging.to_stderr: true
